version: "3"

services:
  postgresdb:
    container_name: cde_bootcamp_postgresdb
    image: postgres:14-alpine
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_HOST=${DB_DOCKER_HOST}
    ports:
      - ${POSTGRES_PORT}:5432
    volumes:
      - postgresdb_data:/var/lib/postgresql/data
    networks:
      - cde_bootcamp_network

  pgadmin:
    container_name: cdebootcamp_pgadmin
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - postgresdb_data:/var/lib/postgresql/data
    ports:
      - ${PGADMIN_PORT}:80
    networks:
      - cde_bootcamp_network

networks:
  cde_bootcamp_network:
    driver: bridge

volumes:
  postgresdb_data:
